services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: btrans
        uid: 1000
    image: btrans-app
    container_name: btrans-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - btrans-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: btrans-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - btrans-network
      - proxy_net

  # MariaDB Service (Plus stable sur VPS Cloud que MySQL 8)
  db:
    image: mariadb:10.11
    container_name: btrans-db
    restart: unless-stopped
    command: --innodb-use-native-aio=0 --innodb-flush-method=O_DSYNC --skip-name-resolve
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - btrans-network

networks:
  btrans-network:
    driver: bridge
  proxy_net:
    external: true
